import {
  Megaphone,
  Globe,
  LayoutDashboard,
  Boxes,
  PenTool,
  Share2,
  Palette,
  Code2,
  Smartphone,
  Camera,
  Video,
  TrendingUp,
  Users,
  Briefcase,
  ShoppingCart,
  Mail,
  Search,
  BarChart3,
  Settings,
  Zap,
  Star,
  Heart,
  Rocket,
  Target,
  Award,
  Layers,
  FileText,
  Image as ImageIcon,
  Database,
  Cloud,
  Shield,
  MessageSquare,
  Building2,
  Wand2,
  Sparkles,
  Wrench,
  PieChart,
  Package as PackageIcon,
  Truck,
  Calendar,
  type LucideIcon,
} from "lucide-react";

// The 6 original services (Digital Marketing, Website Development,
// Dashboard Development, 3D Architecture, Graphic Design, Social Media
// Management) already use the first 6 names below — keep those exact
// keys so existing rows in `services.icon` keep resolving correctly.
export const SERVICE_ICONS: Record<string, LucideIcon> = {
  Megaphone,
  Globe,
  LayoutDashboard,
  Boxes,
  PenTool,
  Share2,
  Palette,
  Code2,
  Smartphone,
  Camera,
  Video,
  TrendingUp,
  Users,
  Briefcase,
  ShoppingCart,
  Mail,
  Search,
  BarChart3,
  Settings,
  Zap,
  Star,
  Heart,
  Rocket,
  Target,
  Award,
  Layers,
  FileText,
  ImageIcon,
  Database,
  Cloud,
  Shield,
  MessageSquare,
  Building2,
  Wand2,
  Sparkles,
  Wrench,
  PieChart,
  PackageIcon,
  Truck,
  Calendar,
};

export const SERVICE_ICON_NAMES = Object.keys(SERVICE_ICONS);

const FALLBACK_ICON: LucideIcon = Layers;

/** Never throws — an unrecognized or missing icon name just falls back. */
export function getServiceIcon(name: string | null | undefined): LucideIcon {
  if (!name) return FALLBACK_ICON;
  return SERVICE_ICONS[name] ?? FALLBACK_ICON;
}
